variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_address" {}
variable "region" {}
variable "security-group-rds-id" {}
variable "security-group-redshift-id" {}
variable "redshift-endpoint" {}
variable "redshift-dns-name" {}
variable "s3_bucket_name" {}
variable "glue_role_arn" {}
variable "subnet-private-subnet-1a-id" {}
